//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Entities")]
[assembly: System.Reflection.AssemblyDescription("My project to solve any issue in the world")]
[assembly: System.Reflection.AssemblyCompany("snowinmars")]
[assembly: System.Reflection.AssemblyProduct("snowinmarsProductName")]
[assembly: System.Reflection.AssemblyCopyright("GNU/GPL")]
[assembly: System.Reflection.AssemblyTrademark("snowinmarsTrademark")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyVersion("1.0.7025.22")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.7025.22")]


